[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# If you use client-side routing (React Router), keep this:
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
